name: tjm_business_platform_logic
description: Logic package for TJM Business platform.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  intl: ^0.20.2
  supabase: ^2.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mockito: ^5.5.1 
  build_runner: ^2.10.3 
